### ISSUE TITLE
Nested Lists not handled

### ISSUE THREAD

**Issue by npcole** [forgeworks/quill-delta-python#6]
Is it something I am doing wring, or are nested lists not handled correctly?

import delta
d = delta.Delta(ops=[
{"insert":"This is a test\nThis is another"},
{"attributes":{"list":"bullet"},"insert":"\n"},
{"insert":"test"},
{"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},
{"insert":"that is quite different"},
{"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},
{"insert":"And this is back at level 1"},
{"attributes":{"list":"bullet"},"insert":"\n"},
])
delta.html.render(d)
'<p>This is a test</p><ul><li>This is another</li><li>test</li><li>that is quite different</li><li>And this is back at level 1</li></ul>'

I'd expect the indented lists to be wrapped in their own ul tag, but instead a flat list is returned.

**Comment by DeadWisdom** [comment]
Definitely an issue, will have a fix as soon as I can. Thanks!

**Comment by Eraldo** [comment]
Are you still on this @DeadWisdom?

I am trying to evaluate if I change my frontend to send deltas instead of hml to my python backend. However I am hesitant to do so if this parser/renderer is not really reliable.

You have every right to do as little or as much as you please. ;)
I'm just trying to get an idea if you are aiming to actively still support this library.
What do you say? 🤔

**Comment by Eraldo** [comment]
Ping? :)

**Comment by DeadWisdom** [comment]
Man, sorry I did not have notifications turned on here. @Eraldo -- it is fixed now. Sorry if it's so late. Feel free to hit me up on twitter @DeadWisdom in the future.
